services:
  - type: worker
    name: telegram-video-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: BOT_TOKEN
        value: <YOUR_TELEGRAM_BOT_TOKEN>
